awac_lambda: 0.1
batch_size: 256
buffer_size: 10000000
checkpoints_path: null
deterministic_torch: false
device: cuda
env_name: antmaze-large-diverse-v2
eval_frequency: 50000
gamma: 0.99
group: awac-antmaze-large-diverse-v2-multiseed-v0
hidden_dim: 256
learning_rate: 0.0003
n_test_episodes: 100
normalize_reward: true
offline_iterations: 1000000
online_iterations: 1000000
project: CORL
seed: 42
tau: 0.005
test_seed: 69